name = "atacenterdeluxe"
compatibility_date = "2024-01-01"

[env.production]
name = "atacenterdeluxe"

[env.preview]
name = "atacenterdeluxe-preview"

# Cloudflare Pages configuration
[pages]
build = { command = "", destination = "." }
